version: "3.8"

services:
  dev-database:
    image: postgres:15 # this aligns with Vercel's serverless Postgres version
    environment:
      #POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_DATABASE: my-test-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] #replace the hardcoded username variable when
      interval: 10s
      timeout: 5s
      retries: 12

  seed-dev-database:
    build:
      dockerfile: docker/dev-database/seedDatabase.Dockerfile
      context: "."
    command: sh -c "npm run db:setup"
    volumes:
      - "./prisma/:/db-setup/prisma/"
    environment:
      DATABASE_URL: "postgresql://postgres:secret@dev-database:5432/my-test-app"
    depends_on:
      dev-database:
        condition: service_healthy
